# YOUR NAME OR TITLE OF YOUR SITE
name: Копирка Одинцово 2

# YOUR BRAND/PERSONAL TAGLINE
tagline: Контакты отделения
# YOUR/BRAND IMAGE URL
Image_URL: https://kopirka.ru/wa-data/public/site/themes/xk/img/logo/logo[0].svg


# CHANGE THE BACKGROUND IMAGE OF THE WEBSITE BY JUST ADDING THE IMAGE URL
#Cover_Image: https://picsum.photos/1080?nocache=

# SOCIAL MEDIA
links:

  # IF YOU DON'T WANT TO USE ANY OF THE FOLLOWING, JUST LEAVE THE URL BLANK
    
    # WHATSAPP
  - Name: WhatsApp
    URL: https://api.whatsapp.com/send?phone=79015602589
    Color: '#25d366'
	Text_Color: '#ffffff'
    Icon-Class: fab fa-whatsapp

    # TELEGRAM
  - Name: Telegram
    URL: https://t.me/
    Username: kopirkaO2
    Color: '#0088cc'
    Icon-Class: fab fa-telegram-plane

    # EMAIL
  - Name: Email
    URL: 'mailto:272@kopirka.ru'
    Icon-Class: fas fa-envelope
    Color: '#e17055'
    Text_Color: '#ffffff'


# YOU CAN REMOVE FOOTER COMPLETELY BY SIMPLY REMOVING EITHER THE YES OR REMOVING THE FOOTER STATEMENT BELOW COMPLETELY
footer: 

# STOP EDITING HERE ---------- YOU'VE REACHED THE END OF THE CONFIGURATION

# Compress
compress_html:
  clippings: all

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Icon

# Base URL
# baseurl: /links

# Default Markdown Engine
markdown: kramdown
